# Generated by Django 3.2.5 on 2022-05-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='昵称')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
    ]
