# Generated by Django 3.2.5 on 2022-05-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_mominfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mominfo',
            name='password',
        ),
    ]
