# Generated by Django 3.2.5 on 2022-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20220529_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('create_time', models.DateField(verbose_name='创建时间')),
                ('contain', models.TextField(verbose_name='博客内容')),
            ],
        ),
        migrations.DeleteModel(
            name='mypicture',
        ),
        migrations.DeleteModel(
            name='PrettyNum',
        ),
    ]
